
disqus:
  config: false
  id: disqus_bERYFJaF1Z

username: 1011641270
baseurl: /blog
markdown: redcarpet
safe: false
highlighter: pygments
title: Tian_dd
description: Make it easier,smaller!
theme: midnight
disqusname: disqus_bERYFJaF1Z
